### 1. Criar Matéria-Prima
POST http://localhost:8080/api/raw-materials
Content-Type: application/json
{
  "name": "Broc33",
  "code": "das3",
  "stockQuantity": -1
}

### 1.1 Deletar uma materia prima
DELETE  http://localhost:8080/api/raw-materials/2

### 1.2 Busca uma materia prima pelo code
GET http://localhost:8080/api/raw-materials/code/MP3424

### 1.3 Atualiza o estoque com valor novo
PATCH  http://localhost:8080/api/raw-materials/11/stock?quantity=-150

### 2.Criar um produto
POST http://localhost:8080/api/products
Content-Type: application/json

{
  "name": "Motor",
  "price": 10000.0,
  "materials": [
    {
      "rawMaterial": { "id": 5 },
      "requiredQuantity": 134.0
    }
  ]
}

### 2.1 Atualizar lista de materia do produto
PUT http://localhost:8080/api/products/7
Content-Type: application/json

[
    {
      "rawMaterial": { "id": 3 },
      "requiredQuantity": 40
    },
  {
    "rawMaterial": { "id": 16 },
    "requiredQuantity": 100
  }
]


### 3. Testar a Sugestão do mais caro ao mais barato
GET http://localhost:8080/api/products/suggest

